### ISSUE TITLE
`env.reset()` hangs waiting for observation to be returned by `GymAI` agent via Pipe with --disable-window set as arguments

### ISSUE THREAD

**Issue by Jazz86** [myt1996/gym-fightingice#3]
Hi FightingICE team!
I'm trying to set the argument "--disable-window" to accelerate my training process but the program stuck eventually.
In Ubuntu 18.04.5, the program stuck about 100s~400s rounds.

#### **Setup:**
1. I have installed all python requirements: `py4j, port_for==0.10.4, gym, opencv-python`(I noticed that there is py4j package in FTG4.50/python folder and its version is 0.10.4, so I assume to use 0.10.4 instead of the latest version. However, then I update the package to 0.10.9.2, it still stuck.)
2. I have downloaded FTG4.50 from [official website](http://www.ice.ci.ritsumei.ac.jp/~ftgaic/index-2.html)
#### **Reproducing the issue:**
example.py:
```
import gym
import gym_fightingice

env = gym.make("FightingiceDataNoFrameskip-v0", java_env_path="correct/path/to/FTG4.50", opponent="DiceAI")
while True:
    obs = env.reset()
    done = False
    while not done:
        action = env.action_space.sample()
        observation, reward, done, info = env.step(action=action)
```
Inside fightingice_env_data_noframeskip.py:
```
114: self.java_env = subprocess.Popen(["java", "-cp", self.start_up_str, "Main", "--port", str(self.port), "--py4j", "--fastmode",
115:                                            "--grey-bg", "--inverted-player", "1", "--mute", "--limithp", "400", "400", "--disable-window"])
```

### **Environment**
Java version:
Command: `java -version`:
```
openjdk version "1.8.0_282"
OpenJDK Runtime Environment (build 1.8.0_282-8u282-b08-0ubuntu1~18.04-b08)
OpenJDK 64-Bit Server VM (build 25.282-b08, mixed mode)
```

Python version:
Command: `python --version`:
```
Python 3.6.11
```

### **Debuging**
I use print to check where the program stuck, and "obs received" never print at the end of the error message below:
```
# ... inside reset() function in class gym_fightingice.envs.FightingiceEnv_Data_NoFrameskip
190: self.pipe.send("reset")
191: self.round_num += 1
192: print("about to recv obs")
193: obs = self.pipe.recv() # <--- Gets stuck here
194: print("obs received") 
195: return obs
```

### **error message**
```
<class 'numpy.ndarray'>
send round end to <multiprocessing.connection.Connection object at 0x7f02c970cb38>
round:  424 2021-03-08 16:38:35.505011
0
125
2409
Mar 08, 2021 4:38:35 PM gamescene.Play update
INFO: Game over
Exception in thread "main" py4j.Py4JException: Error while sending a command.
        at py4j.CallbackClient.sendCommand(CallbackClient.java:357)
        at py4j.CallbackClient.sendCommand(CallbackClient.java:316)
        at py4j.reflection.PythonProxyHandler.invoke(PythonProxyHandler.java:103)
        at com.sun.proxy.$Proxy0.close(Unknown Source)
        at aiinterface.AIController.gameEnd(AIController.java:224)
        at manager.InputManager.closeAI(InputManager.java:245)
        at gamescene.Play.close(Play.java:384)
        at manager.GameManager.update(GameManager.java:57)
        at manager.DisplayManager.gameLoop(DisplayManager.java:166)
        at manager.DisplayManager.start(DisplayManager.java:53)
        at Main.main(Main.java:22)
Caused by: py4j.Py4JNetworkException
        at py4j.CallbackConnection.sendCommand(CallbackConnection.java:138)
        at py4j.CallbackClient.sendCommand(CallbackClient.java:344)
        ... 10 more
Start java env in . and port 24807
ERROR:root:Exception while sending command.
Traceback (most recent call last):
  File "/home/user/Apps/miniconda3/envs/drl/lib/python3.6/site-packages/py4j/java_gateway.py", line 1035, in send_command
    raise Py4JNetworkError("Answer from Java side is empty")
py4j.protocol.Py4JNetworkError: Answer from Java side is empty

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/user/Apps/miniconda3/envs/drl/lib/python3.6/site-packages/py4j/java_gateway.py", line 883, in send_command
    response = connection.send_command(command)
  File "/home/user/Apps/miniconda3/envs/drl/lib/python3.6/site-packages/py4j/java_gateway.py", line 1040, in send_command
    "Error while receiving", e, proto.ERROR_ON_RECEIVE)
py4j.protocol.Py4JNetworkError: Error while receiving
Please IGNORE the Exception above because of restart java game
Mar 08, 2021 4:38:39 PM manager.InputManager <init>
INFO: Create instance: manager.InputManager
Mar 08, 2021 4:38:39 PM manager.DisplayManager initialize
INFO: Disable window mode
Mar 08, 2021 4:38:39 PM manager.GraphicManager <init>
INFO: Create instance: manager.GraphicManager
Mar 08, 2021 4:38:39 PM loader.ResourceLoader <init>
INFO: Create instance: loader.ResourceLoader
Python
about to recv obs
Mar 08, 2021 4:38:41 PM gamescene.Launcher update
INFO: Transition to PLAY
Mar 08, 2021 4:38:41 PM util.LogWriter <init>
INFO: Create instance: util.LogWriter
Mar 08, 2021 4:38:41 PM aiinterface.AIController run
INFO: Start to run
Mar 08, 2021 4:38:41 PM aiinterface.AIController run
INFO: Start to run
```
Thank you all for your help!!

**Comment by myt1996** [comment]
This repository only supports until FightingICE 4.30.
You may try [latest version of Gym-FightingICE](https://github.com/TeamFightingICE/Gym-FightingICE).
If you still have this problem, please open a new issue there or contact Team FightingICE by E-mail.
The E-mail address can be found at [FightingICE offical site](http://www.ice.ci.ritsumei.ac.jp/~ftgaic/index-5.html).

**Comment by Jazz86** [comment]
Thank you for your reply!
